name: MangaReaderScraper

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # TODO: versions are executed concurrently, find a way to have both them
    #       in the same build
    # NOTE: py3.8 fails die to lxml error
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [ubuntu-latest]
    #     python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Test with Tox
        run: tox -e py
